export const ielts = {
  'IELTS 1': [
    { index: 816, words_eng: 'accommodation', translate: 'вид проживання( готель, кімната)' },
    { index: 816, words_eng: 'all holiday', translate: 'час після втрати роботи' },
    { index: 816, words_eng: 'half-board', translate: 'з влюченим сніданком і вечерею' },
    { index: 816, words_eng: 'full-board', translate: 'трьох разове харчування, без алкоголю' },
    { index: 816, words_eng: 'self-catering', translate: 'без харчування' },
    { index: 816, words_eng: 'breathtaking view', translate: 'зачаровуючий вид' },
    { index: 816, words_eng: "busman's holiday", translate: 'працівник у свята' },
    { index: 816, words_eng: 'far-off destination', translate: 'віддалене місце' },
    { index: 816, words_eng: 'getting away from it all', translate: 'втекти від всьго' },
    { index: 816, words_eng: 'go off the beaten track', translate: 'йти незнайомою дорогою' },
    { index: 816, words_eng: 'head for', translate: 'націлений на наступну місцевість' },
    {
      index: 816,
      words_eng: 'holiday of a lifetime',
      translate: 'унікальний відпочинок, раз життя',
    },
    { index: 816, words_eng: 'holiday resort (tourist resort)', translate: 'популярний курорт' },
    { index: 816, words_eng: 'hordes of tourists', translate: 'натовп туристів' },
    {
      index: 816,
      words_eng: 'in the middle of nowhere',
      translate: 'місце далеке від місцевості( село)',
    },
    { index: 816, words_eng: 'local crafts', translate: 'місцеві речі' },
    { index: 816, words_eng: 'out of season', translate: 'не в сезов' },
    { index: 816, words_eng: 'picturesque village', translate: 'чудове село' },
    { index: 816, words_eng: 'places of interest', translate: 'чудові місця місцевості' },
    { index: 816, words_eng: 'short break', translate: 'короткий відпочинок' },
    { index: 816, words_eng: 'stunning landscape', translate: 'захоплюючі ланшафти' },
    { index: 816, words_eng: 'to go sightseeing', translate: 'відвідувати памятки' },
    { index: 816, words_eng: 'to travel on foot ', translate: 'подорожувати ногами' },
    { index: 816, words_eng: 'tourist attractions', translate: 'місця відвідин туристів' },
    { index: 816, words_eng: 'tourist trap', translate: 'місце з багатьма туристами' },
    { index: 816, words_eng: 'wildlife safari', translate: 'відпочинок в сафарі' },
  ],
  'IELTS 2': [
    {
      index: 816,
      words_eng: "enjoy each other's company",
      translate: 'насолоджуватись компанією один одного',
    },
    {
      index: 816,
      words_eng: 'fair-weather friend',
      translate: 'друг який з тобою коли ти багатий або веселий',
    },
    { index: 816, words_eng: 'get in touch with somebody', translate: 'сконтактуватись з кимось' },
    {
      index: 816,
      words_eng: 'near and dear to someone',
      translate: 'хтось дуже важливий для когось',
    },
    {
      index: 816,
      words_eng: 'shoulder to cry on',
      translate: 'хтось хто готовий слухати проблеми',
    },
    {
      index: 816,
      words_eng: 'to be through thick and thin',
      translate: 'мати хороші і важкий час разом',
    },
    { index: 816, words_eng: 'to be well-matched', translate: 'співпадати з кимось інтересами' },
    { index: 816, words_eng: 'drift apart', translate: 'стати менш близьким до когось' },
    { index: 816, words_eng: 'fall for someone', translate: 'закохатись в когось' },
    { index: 816, words_eng: 'fall out with', translate: 'сваритись' },
    { index: 816, words_eng: 'get on like a house on fire', translate: 'швидко ладнати з кимось' },
    { index: 816, words_eng: 'get on well with somebody', translate: 'мати хороші стосунки з' },
    { index: 816, words_eng: 'get to know someone', translate: 'познайомитись з кимось' },
    { index: 816, words_eng: 'have a lot in common', translate: 'мати багато спільного' },
    { index: 816, words_eng: 'have friends in high places', translate: 'мати впливових друзів' },
    {
      index: 816,
      words_eng: 'hit it off with somebody',
      translate: 'швидко подружитися з ким-небудь',
    },
    {
      index: 816,
      words_eng: 'keep in touch with someone',
      translate: 'підтримувати контакт з кимось',
    },
    { index: 816, words_eng: 'lose touch with someone', translate: 'втратити звязок з кимось' },
    { index: 816, words_eng: 'to see eye to eye', translate: 'погодитись' },
    { index: 816, words_eng: 'strike up', translate: 'почати ( розмову, стосунки)' },
    {
      index: 816,
      words_eng: 'ups and downs',
      translate: 'суміш хороших і поганих речей, які трапляються',
    },
  ],
  'IELTS 3': [
    { index: 816, words_eng: 'computer buff', translate: 'добре володіє компютером' },
    { index: 816, words_eng: 'computer fatigue', translate: 'синдром втоми від компютера' },
    { index: 816, words_eng: 'cutting-edge', translate: 'щось інноваційне та провідне' },
    { index: 816, words_eng: 'digital editing', translate: 'процес зміни відео і аудіо файлів' },
    {
      index: 816,
      words_eng: 'essential',
      translate: 'без чого не можеш уявити своє життя, важливий',
    },
    { index: 816, words_eng: 'geek', translate: 'той хто одержимий технологіями/компютером' },
    { index: 816, words_eng: 'hold the line', translate: 'почекай хвилинку' },
    { index: 816, words_eng: 'light years ahead', translate: 'дуже далеко від' },
    { index: 816, words_eng: 'on the cutting edge', translate: 'попереду прогресу' },
    { index: 816, words_eng: 'out of steam', translate: 'змучений, виснажений' },
    { index: 816, words_eng: 'rocket science', translate: 'важкий предмет для когось' },
    { index: 816, words_eng: 'send an attachment', translate: 'відправити імейл із файлом' },
    {
      index: 816,
      words_eng: 'silver surfer',
      translate: 'старша людина яка користується інтернетом',
    },
    {
      index: 816,
      words_eng: 'time-consuming and inefficient',
      translate: 'щось що забирає багато часу і не є раціональним',
    },
    { index: 816, words_eng: 'to access websites', translate: 'відвідити сайти' },
    { index: 816, words_eng: 'back up files', translate: 'копія фалів' },
    {
      index: 816,
      words_eng: 'be stuck behind a computer',
      translate: 'сидіти довго за компютером',
    },
    { index: 816, words_eng: 'boot up', translate: 'включити компютер' },
    { index: 816, words_eng: 'pull the plug', translate: 'закінчити щось' },
    { index: 816, words_eng: 'to surf the web', translate: 'шукати щось в інтернеті' },
    { index: 816, words_eng: 'well-oiled machine', translate: 'щось що добре працює' },
    {
      index: 816,
      words_eng: 'widespread computer use',
      translate: 'люди які часто використовують компютер',
    },
    { index: 816, words_eng: 'wireless network', translate: 'безкабельний інтернет' },
    { index: 816, words_eng: 'word processing', translate: 'набирати і редагувати текст' },
  ],
  'IELTS 4': [
    { index: 816, words_eng: 'active rest', translate: 'відпочинок із спортом' },
    { index: 816, words_eng: 'athletics track (running track)', translate: 'доріжка для бігу' },
    { index: 816, words_eng: 'barbell', translate: 'штанга' },
    { index: 816, words_eng: 'blow the competition away', translate: 'легко виграти змагання' },
    { index: 816, words_eng: 'brisk walk', translate: 'швидка ходьба' },
    { index: 816, words_eng: 'to build muscle', translate: "набрати м'язову масу" },
    { index: 816, words_eng: 'keep-fit exercises', translate: 'вправи для хорошого тіла' },
    { index: 816, words_eng: 'personal best', translate: 'досягнення в спорті' },
    {
      index: 816,
      words_eng: 'sports centre',
      translate: 'будівля для різних видів спорту (бокс, гімнастика ітд)',
    },
    { index: 816, words_eng: 'sports facilities', translate: 'тренаджери+ сервіс( доатково)' },
    { index: 816, words_eng: 'sports meeting', translate: 'спортивні заняття' },
    {
      index: 816,
      words_eng: 'strength-training strategy',
      translate: 'стратегія силових тренувань',
    },
    { index: 816, words_eng: 'strenuous exercise', translate: 'важкі фізичні навантаження' },
    { index: 816, words_eng: 'strong swimmer', translate: 'досвідчений плавець' },
    {
      index: 816,
      words_eng: "that's the way the ball bounces",
      translate: 'не все йде як планувалось',
    },
    { index: 816, words_eng: 'to be keen to do smth', translate: 'мати бажання робити що-небудь' },
    {
      index: 816,
      words_eng: 'to be out of condition',
      translate: 'бути в поганому фізичному стані, втрачати сили',
    },
    {
      index: 816,
      words_eng: 'to be saved by the bell',
      translate: 'вчасно зупинитись щоь не програти',
    },
    { index: 816, words_eng: 'get into shape', translate: 'прийти до форми' },
    { index: 816, words_eng: 'keep fit', translate: 'підтримувати фотму' },
    { index: 816, words_eng: 'take up doing smth', translate: 'почати займатись новим спортом' },
    { index: 816, words_eng: 'warm up', translate: 'розігрівка перед тренуванням' },
    { index: 816, words_eng: 'work out', translate: 'тренування' },
    {
      index: 816,
      words_eng: 'trial-and-error method',
      translate: 'різні методи для успіху(позитивні і ні)',
    },
    { index: 816, words_eng: 'workout', translate: 'сеанс вправ у тренажерному залі' },
    { index: 816, words_eng: 'fencing', translate: 'фехтування' },
    { index: 816, words_eng: 'hurdles', translate: 'біг через перешкоди' },
    { index: 816, words_eng: 'javelin', translate: 'спорт із метання спису' },
    { index: 816, words_eng: 'pole vault', translate: 'стрибки у висоту із списом' },
    { index: 816, words_eng: 'steeplechase', translate: 'стрибки на конях через перешкоди' },
  ],
  'IELTS 5': [
    { index: 816, words_eng: 'dine in', translate: 'обід дома' },
    { index: 816, words_eng: 'dine out', translate: 'обід в ресторані' },
    { index: 816, words_eng: 'fussy eater', translate: 'той хто вимогливий до їжі' },
    { index: 816, words_eng: 'in a walking distance of', translate: 'близько до' },
    {
      index: 816,
      words_eng: 'more of a chore than a pleasure',
      translate: 'те що робите більш неохоче',
    },
    { index: 816, words_eng: 'mouth-watering', translate: 'смачно' },
    { index: 816, words_eng: 'my mouth is watering', translate: 'а ж слюньки течуть' },
    { index: 816, words_eng: 'nutritious products', translate: 'калорійні продукти' },
    { index: 816, words_eng: 'processed food', translate: 'перероблена їжа, нездорова' },
    { index: 816, words_eng: 'quality justifies the bill', translate: 'якість перевищує ціну' },
    { index: 816, words_eng: 'quick snack', translate: 'швидкий перекус' },
    {
      index: 816,
      words_eng: "restrain one's hunger",
      translate: 'уникання того що хочеш істи, через дієту',
    },
    { index: 816, words_eng: 'slap-up meal', translate: 'швидка і жирна їжа' },
    { index: 816, words_eng: 'starving hungry', translate: 'дуже голодний' },
    { index: 816, words_eng: 'to be dying of hunger!', translate: 'помираю з голоду!' },
    { index: 816, words_eng: 'to be full-up', translate: 'наїстись' },
    { index: 816, words_eng: 'to be ravenous', translate: 'справді голодний' },
    { index: 816, words_eng: 'bolt something down', translate: 'істи багато швидко' },
    { index: 816, words_eng: 'catch a snack', translate: 'їсти малі порції швидко' },
    {
      index: 816,
      words_eng: 'to eat a balanced diet',
      translate: 'правильно і вчасно харчуватися',
    },
    { index: 816, words_eng: 'to eat like a horse', translate: 'завжди їсти багато' },
    { index: 816, words_eng: 'to foot the bill', translate: 'заплатиити рахунок' },
    { index: 816, words_eng: 'to grab a bite to eat', translate: 'швидко щось зїсти' },
    { index: 816, words_eng: 'to have a sweet tooth', translate: 'багато істи солодкого' },
    { index: 816, words_eng: 'to overeat', translate: 'переїдати' },
    { index: 816, words_eng: 'to tuck into smth', translate: 'поїдати щось жадібно' },
    { index: 816, words_eng: 'to wine and dine', translate: 'бенкет' },
    { index: 816, words_eng: 'to work up an appetite', translate: 'розігнати апетит' },
  ],
};
