export const other = {
  'friends 1': [
    { index: 685, words_eng: 'get to', translate: 'мати можливість' },
    { index: 686, words_eng: 'be all over', translate: 'не давати ступити кроку' },
    { index: 687, words_eng: 'herd', translate: 'стадо, табун' },
    { index: 688, words_eng: 'pick off', translate: 'убивати відривати' },
    { index: 689, words_eng: 'look after', translate: 'піклуватись' },
    { index: 690, words_eng: 'odds', translate: 'шанси, ставки, коефіціент' },
    { index: 691, words_eng: 'let it go', translate: 'відпусти, не переймайся' },
    { index: 692, words_eng: 'bashing', translate: 'напади, биття' },
    { index: 693, words_eng: 'pick at', translate: 'придиратись до, чіплятись' },
    { index: 694, words_eng: 'go out with', translate: 'зустрічатись' },
    { index: 695, words_eng: 'crooked', translate: 'крива, викривлена' },
    { index: 696, words_eng: 'nursery rhyme', translate: 'дитячий вірш' },
    { index: 697, words_eng: 'a thing or two', translate: 'дещо' },
    { index: 698, words_eng: 'innate', translate: 'вроджене, природнє' },
    { index: 699, words_eng: 'vowels', translate: 'голосні' },
    { index: 700, words_eng: 'unfair', translate: 'несправедливо' },
    { index: 701, words_eng: 'flaw', translate: 'недолік, вада (людини)' },
    { index: 702, words_eng: 'snort', translate: 'хрюкання' },
    { index: 703, words_eng: 'chew', translate: 'жувати' },
    { index: 704, words_eng: 'endearing', translate: 'мило, чарівно' },
    { index: 705, words_eng: 'come out', translate: 'появлятись, вилазити' },
    { index: 706, words_eng: 'come off', translate: 'спадають (взуття)' },
    { index: 707, words_eng: 'glove', translate: 'рукавиця' },
    { index: 708, words_eng: 'get over', translate: 'пережити ( хворобу ітд)' },
    { index: 709, words_eng: 'now and then', translate: 'час від часу' },
    { index: 710, words_eng: 'underwear', translate: 'нижня білизна' },
    { index: 711, words_eng: 'break up with', translate: 'перестати зустрічатись' },
    { index: 712, words_eng: 'relieved', translate: 'полекшення' },
    { index: 713, words_eng: "can't stand", translate: 'не переносити щось, не можна терпіти' },
    { index: 714, words_eng: 'stay over', translate: 'лишитись на ніч' },
    { index: 715, words_eng: 'bring down', translate: 'портити настрій' },
    { index: 716, words_eng: 'spy on', translate: 'слідкувати' },
    { index: 717, words_eng: 'get up the courage', translate: 'набиратись мужності' },
    { index: 718, words_eng: 'going up on', translate: 'наїхати на' },
    { index: 719, words_eng: 'burn up', translate: 'бісити' },
    { index: 720, words_eng: 'rip apart', translate: 'рвати на частини' },
    { index: 721, words_eng: 'tongue', translate: 'язик' },
    { index: 722, words_eng: 'aware', translate: 'усвідомлений, поінформований' },
    { index: 723, words_eng: 'candle', translate: 'свічка' },
  ],
  'reported speech': [
    { index: 816, words_eng: 'admit', translate: 'зізнаватись' },
    { index: 816, words_eng: 'deny', translate: 'заперечувати' },
    { index: 816, words_eng: 'suggest', translate: 'запропонувати' },
    { index: 816, words_eng: 'apologise for', translate: 'вибачатись за' },
    { index: 816, words_eng: 'insist on', translate: 'наполягати на' },
    { index: 816, words_eng: 'accuse sb of', translate: 'звинувачувати когось в' },
    { index: 816, words_eng: 'complain to sb of/about', translate: 'нарікати на щось' },
    { index: 816, words_eng: 'boast of/about', translate: 'вихвалятись за/про' },
    { index: 816, words_eng: 'warn sb of/about', translate: 'попереджати' },
    { index: 816, words_eng: 'beg', translate: 'благати' },
    { index: 816, words_eng: 'warn', translate: 'попередити' },
    { index: 816, words_eng: 'insist on', translate: 'наполягати' },
    { index: 816, words_eng: 'refuse', translate: 'відмовитися' },
  ],
};
