export const units = {
  3: [
    { index: 302, words_eng: 'beat', translate: 'перемогти, бити' },
    { index: 303, words_eng: 'board game', translate: 'настільна гра' },
    { index: 304, words_eng: 'cheat', translate: 'обманювати , обман' },
    { index: 305, words_eng: 'defeat', translate: 'поразка, розгром' },
    { index: 306, words_eng: 'entertaining', translate: 'розважальний, цікавий' },
    { index: 307, words_eng: 'folk', translate: 'фолькльорний, народний' },
    { index: 308, words_eng: 'pleasure', translate: 'задоволення' },
    { index: 309, words_eng: 'rhythm', translate: 'ритм' },
    { index: 310, words_eng: 'train', translate: 'поїзд, тренувати' },
    { index: 311, words_eng: 'carry on', translate: 'продовжити' },
    { index: 312, words_eng: 'support', translate: 'вболівати' },
    { index: 313, words_eng: 'eat out', translate: 'їсти не дома' },
    { index: 314, words_eng: 'give up', translate: 'зупинити регулярну роботу' },
    { index: 315, words_eng: 'send off', translate: 'вигнати гравця з поля(по правилам)' },
    { index: 316, words_eng: 'join in', translate: 'приєднюватись' },
    { index: 317, words_eng: 'take up', translate: 'почати займатись(хоббі, спортом і тд) -новим' },
    { index: 318, words_eng: 'hide-and-seek', translate: 'хованки' },
    { index: 319, words_eng: 'listen to', translate: 'прислухатись до' },
    { index: 320, words_eng: 'book by', translate: 'книга (автор)' },
    { index: 321, words_eng: 'crazy about', translate: 'без розуму від' },
    { index: 322, words_eng: 'good at', translate: 'добрий(хороший) в' },
    { index: 323, words_eng: 'keep on', translate: 'продовжити дратівливо говорити' },
    { index: 324, words_eng: 'popular with', translate: 'популярний серед' },
    { index: 325, words_eng: 'feel like', translate: 'поводитись як' },
    { index: 326, words_eng: 'game against', translate: 'гра проти' },
    { index: 327, words_eng: 'take down', translate: 'записувати, фотографувати, складати щось' },
    { index: 328, words_eng: 'take off', translate: 'стартувати, набирати оборотів' },
    { index: 329, words_eng: 'turn up', translate: 'підкрутити' },
    { index: 330, words_eng: 'turn down', translate: 'скрутити' },
    { index: 331, words_eng: 'warm up', translate: 'розігрівати, зігріватись' },
    { index: 332, words_eng: 'firefighter', translate: 'пожарник' },
    { index: 333, words_eng: 'briefly', translate: 'коротко' },
    { index: 334, words_eng: 'escape', translate: 'вирватись, втеча' },
    { index: 335, words_eng: 'cage', translate: 'клітка' },
    { index: 336, words_eng: 'keen on', translate: 'захоплюватись' },
    { index: 337, words_eng: 'inactive', translate: 'неактивний' },
    { index: 338, words_eng: 'stairs', translate: 'сходи' },
    { index: 339, words_eng: 'provide', translate: 'забезпечувати' },
    { index: 340, words_eng: 'loudly', translate: 'голосно' },
  ],
  6: [
    { index: 341, words_eng: 'achieve', translate: 'досягати, здобувати' },
    { index: 342, words_eng: 'consider', translate: 'обдумати, брати до уваги' },
    { index: 343, words_eng: 'experience', translate: 'пережити, досвід' },
    { index: 344, words_eng: 'expert', translate: 'знавець, кваліфікований' },
    { index: 345, words_eng: 'fail', translate: 'зазнати невдачі, невдача' },
    { index: 346, words_eng: 'guess', translate: 'здогадуватись, припущення' },
    { index: 347, words_eng: 'hesitate', translate: 'вагатись, сумінватись' },
    { index: 348, words_eng: 'make sure', translate: 'перевіряти, переконуватись' },
    { index: 349, words_eng: 'mark', translate: 'позначка, позначати' },
    { index: 350, words_eng: 'mental', translate: 'психічний, розумовий' },
    { index: 351, words_eng: 'pass', translate: 'проїхати, проходити' },
    { index: 352, words_eng: 'remind', translate: 'нагадати' },
    { index: 353, words_eng: 'cross out', translate: 'закрестити' },
    { index: 354, words_eng: 'point out', translate: 'указувати(важливу інформацію)' },
    { index: 355, words_eng: 'read out', translate: 'читати вголос' },
    { index: 356, words_eng: 'rip up', translate: 'порвати на куски' },
    { index: 357, words_eng: 'rub out', translate: 'стирати' },
    { index: 358, words_eng: 'turn over', translate: 'повернути до себе' },
    { index: 359, words_eng: 'write down', translate: 'записувати' },
    { index: 360, words_eng: 'revise', translate: 'переглядати' },
    { index: 361, words_eng: 'subject', translate: 'предмет' },
    { index: 362, words_eng: 'take an exam', translate: 'скласти іспит' },
    { index: 363, words_eng: 'wonder', translate: 'дивуватись, цікавитись' },
    { index: 364, words_eng: 'for instance', translate: 'наприклад' },
    { index: 365, words_eng: 'in conclusion', translate: 'на закінчення( як висновок)' },
    { index: 366, words_eng: 'in favour', translate: 'на користь' },
    { index: 367, words_eng: 'in general', translate: 'загалом' },
    { index: 368, words_eng: 'divide', translate: 'ділити' },
    { index: 369, words_eng: 'instruct', translate: 'інструктувати' },
    { index: 370, words_eng: 'memory', translate: 'память' },
    { index: 371, words_eng: 'memorize', translate: 'вивчити на память' },
    { index: 372, words_eng: 'refer', translate: 'відноситись, звертатись до чогось' },
    { index: 373, words_eng: 'silent', translate: 'тихий, мовчазний' },
    { index: 374, words_eng: 'silence', translate: 'тиша' },

    { index: 375, words_eng: 'wizard', translate: 'чарівник' },
    { index: 376, words_eng: 'rumor', translate: 'чутки' },
    { index: 377, words_eng: 'afraid', translate: 'переляканий' },
    { index: 378, words_eng: 'wise', translate: 'мудрий' },
    { index: 379, words_eng: 'trust', translate: 'довіряти' },
    { index: 380, words_eng: 'tyke', translate: 'дворняжка' },
    { index: 381, words_eng: 'sweetheart', translate: 'коханий, кохана' },
    { index: 382, words_eng: 'fit', translate: 'підходити (одяг)' },
    { index: 383, words_eng: 'suit', translate: 'підходити під лице' },
    { index: 384, words_eng: 'match', translate: 'підходити під щось' },
    { index: 385, words_eng: 'cupboard', translate: 'комірка' },
    { index: 386, words_eng: 'stairs', translate: 'сходи' },
    { index: 387, words_eng: 'wake', translate: 'будити' },
    { index: 388, words_eng: 'queue', translate: 'черга' },
    { index: 389, words_eng: 'disaster', translate: 'катастрофа' },
    { index: 390, words_eng: 'reference', translate: 'посилання' },
    { index: 391, words_eng: 'capable of', translate: 'буди здатним' },
    { index: 392, words_eng: 'confused', translate: 'заплутаний' },
  ],
  9: [
    { index: 393, words_eng: 'accommodation', translate: 'розміщення, зручності(проживання)' },
    { index: 394, words_eng: 'break', translate: 'перерва' },
    { index: 395, words_eng: 'cancel', translate: 'відміняти' },
    { index: 396, words_eng: 'convenient', translate: 'зручний, комфортний(зручності)' },
    { index: 397, words_eng: 'crash in', translate: 'аварія, розтрощити' },
    { index: 398, words_eng: 'crowded', translate: 'переповнений' },
    { index: 399, words_eng: 'cruise', translate: 'круїзне судно' },
    { index: 400, words_eng: 'delay', translate: 'затримка, затриманий' },
    { index: 401, words_eng: 'destination', translate: 'місце призначення' },
    { index: 402, words_eng: 'ferry', translate: 'паром' },
    { index: 403, words_eng: 'flight', translate: 'політ' },
    { index: 404, words_eng: 'foreign', translate: 'закордонний, іноземний' },
    { index: 405, words_eng: 'harbour', translate: 'гавань, порт' },
    { index: 406, words_eng: 'luggage', translate: 'багаж' },
    { index: 407, words_eng: 'nearby', translate: 'поблизу' },
    { index: 408, words_eng: 'pack', translate: 'упаковка' },
    { index: 409, words_eng: 'platform', translate: 'перон' },
    { index: 410, words_eng: 'reach', translate: 'досягати' },
    { index: 411, words_eng: 'resort', translate: 'курорт' },
    { index: 412, words_eng: 'souvenir', translate: 'сувенір' },
    { index: 413, words_eng: 'traffic', translate: 'дорожні затори' },
    { index: 414, words_eng: 'trip', translate: 'ділова поїздка' },
    { index: 415, words_eng: 'vehicle', translate: 'транспортний засіб' },
    { index: 416, words_eng: 'get in', translate: 'сісти в машину' },
    { index: 417, words_eng: 'get out', translate: 'вийти з машини' },
    { index: 418, words_eng: 'get on', translate: 'сісти в поїзд,автобус і тд' },
    { index: 419, words_eng: 'get off', translate: 'вийти з поїзда,автобуса і тд' },
    { index: 420, words_eng: 'go away', translate: 'залишити місце' },
    { index: 421, words_eng: 'set off', translate: 'відправитись у подож' },
    { index: 422, words_eng: 'take off', translate: 'злетіти' },
    { index: 423, words_eng: 'on schedule', translate: 'за графіком (розкладом)' },
    { index: 424, words_eng: 'on the coast', translate: 'на узбережжі' },
    { index: 425, words_eng: 'attract', translate: 'приваблювати, звертати увагу' },
    { index: 426, words_eng: 'attractive', translate: 'привабливий' },
    { index: 427, words_eng: 'attraction', translate: 'приваблевість,тяжіння' },
    { index: 428, words_eng: 'choice', translate: 'вибір' },
    { index: 429, words_eng: 'uncomfortable', translate: 'не комфортний' },
    { index: 430, words_eng: 'depart', translate: 'відправлятись ,відійти' },
    { index: 431, words_eng: 'depart ture', translate: 'відправлення, відʼїзд' },
    { index: 432, words_eng: 'direct', translate: 'приямий' },
    { index: 433, words_eng: 'direction', translate: 'наприямок' },
    { index: 434, words_eng: 'visitor', translate: 'відвідувач' },
    { index: 435, words_eng: 'close to', translate: 'близько до' },
    { index: 436, words_eng: 'famous for', translate: 'відомий за' },
    { index: 437, words_eng: 'far from', translate: 'далеко від' },
    { index: 438, words_eng: 'late for', translate: 'пізно на щось' },
    { index: 439, words_eng: 'suitable for', translate: 'підходить для' },
    { index: 440, words_eng: 'abroad', translate: 'за кордоном' },
    { index: 441, words_eng: 'provide sb with ', translate: 'надати комусь щось' },
  ],
  12: [
    { index: 442, words_eng: 'apologise', translate: 'вибачатись' },
    { index: 443, words_eng: 'confident', translate: 'впевнений' },
    { index: 444, words_eng: 'cool', translate: 'крутий, прохолодний' },
    { index: 445, words_eng: 'defend', translate: 'захищати' },
    { index: 446, words_eng: 'divorced', translate: 'розведений' },
    { index: 447, words_eng: 'generous', translate: 'щедрий' },
    { index: 448, words_eng: 'grateful', translate: 'вдячний' },
    { index: 449, words_eng: 'independent', translate: 'незалежний' },
    { index: 450, words_eng: 'introduce', translate: 'представляти' },
    { index: 451, words_eng: 'loyal', translate: 'вірний' },
    { index: 452, words_eng: 'neighborhood', translate: 'сусідство' },
    { index: 453, words_eng: 'patient', translate: 'терплячий' },
    { index: 454, words_eng: 'recognise', translate: 'розпізнавати' },
    { index: 455, words_eng: 'relation', translate: 'відносини' },
    { index: 456, words_eng: 'rent', translate: 'оренда' },
    { index: 457, words_eng: 'single', translate: 'поодинокий' },
    { index: 458, words_eng: 'stranger', translate: 'незнайомець' },
    { index: 459, words_eng: 'bring up', translate: 'виховувати (доглядати за)' },
    { index: 460, words_eng: 'fall out with', translate: 'посваритись' },
    { index: 461, words_eng: 'get on with', translate: 'ладити з кимось' },
    { index: 462, words_eng: 'go out with', translate: 'зустрічатись з' },
    { index: 463, words_eng: 'grow up', translate: 'зростати' },
    { index: 464, words_eng: 'let down', translate: 'розчаровувати, підводити' },
    { index: 465, words_eng: 'look after', translate: 'доглядати за' },
    { index: 466, words_eng: 'split up', translate: 'розійтись(кінець відносин)' },
    { index: 467, words_eng: 'by yourself', translate: 'самому' },
    { index: 468, words_eng: 'in common', translate: 'мати спільне' },
    { index: 469, words_eng: 'on purpose', translate: 'на меті' },
    { index: 470, words_eng: 'able', translate: 'здатний' },
    { index: 471, words_eng: 'ability', translate: 'здатність' },
    { index: 472, words_eng: 'disabled', translate: 'інвалід, нездатний' },
    { index: 473, words_eng: 'unable', translate: 'не в змозі' },
    { index: 474, words_eng: 'admire', translate: 'обожнювати' },
    { index: 475, words_eng: 'admiration', translate: 'захоплення' },
    { index: 476, words_eng: 'care', translate: 'турбуватись' },
    { index: 477, words_eng: 'careful', translate: 'турботливий' },
    { index: 478, words_eng: 'careless', translate: 'безтурботний' },
    { index: 479, words_eng: 'confidence', translate: 'впевненість' },
    { index: 480, words_eng: 'forgive', translate: 'прощати' },
    { index: 481, words_eng: 'forgiveness', translate: 'пробачення' },
    { index: 482, words_eng: 'dishonest', translate: 'не чесний' },
    { index: 483, words_eng: 'honesty', translate: 'чесність' },
    { index: 484, words_eng: 'introduction', translate: 'представлення' },
    { index: 485, words_eng: 'liar', translate: 'брехун' },
    { index: 486, words_eng: 'lying', translate: 'брехня' },
    { index: 487, words_eng: 'personality', translate: 'персональність' },
    { index: 488, words_eng: 'relate', translate: 'відноситись, відданий' },
    { index: 489, words_eng: 'relative', translate: 'родич' },
    { index: 490, words_eng: 'fond of', translate: 'любити, подобатись' },
    { index: 491, words_eng: 'jealous of', translate: 'заздрити чомусь' },
    { index: 492, words_eng: 'kind to', translate: 'бути добрим до' },
    { index: 493, words_eng: 'married to', translate: 'вийти заміж за' },
    { index: 494, words_eng: 'proud of', translate: 'бути гордим за' },
    { index: 495, words_eng: 'argue about', translate: 'посеречатись про' },
    { index: 496, words_eng: 'care about', translate: 'підклувватись про' },
  ],
  15: [
    { index: 497, words_eng: 'advertisement', translate: 'реклама' },
    { index: 498, words_eng: 'afford', translate: 'дозволити собі' },
    { index: 499, words_eng: 'bargain', translate: 'вигідна покупка' },
    { index: 500, words_eng: 'catalogue', translate: 'каталог, список' },
    { index: 501, words_eng: 'cost', translate: 'ціна' },
    { index: 502, words_eng: 'debt', translate: 'кредит' },
    { index: 503, words_eng: 'demand', translate: 'попит, вимагати' },
    { index: 504, words_eng: 'fee', translate: 'чайові' },
    { index: 505, words_eng: 'obtain', translate: 'отримувати, добиватись' },
    { index: 506, words_eng: 'owe', translate: 'бути винним (в боргу)' },
    { index: 507, words_eng: 'profit', translate: 'прибуток' },
    { index: 508, words_eng: 'property', translate: 'власність' },
    { index: 509, words_eng: 'purchase', translate: 'покупка, купляти' },
    { index: 510, words_eng: 'receipt', translate: 'чек, квитанція' },
    { index: 511, words_eng: 'require', translate: 'вимагати' },
    { index: 512, words_eng: 'supply', translate: 'постачати, постачання' },
    { index: 513, words_eng: 'variety', translate: 'різновид' },
    { index: 514, words_eng: 'waste', translate: 'тратити' },
    { index: 515, words_eng: 'add up', translate: 'підсумувати щось' },
    { index: 516, words_eng: 'come back', translate: 'повертатись' },
    { index: 517, words_eng: 'give away', translate: 'віддавати на благодійність' },
    { index: 518, words_eng: 'hurry up', translate: 'поспішати' },
    { index: 519, words_eng: 'save up for', translate: 'відкладати для' },
    { index: 520, words_eng: 'take down', translate: 'повернути щось' },
    { index: 521, words_eng: 'take down', translate: 'зняти щось' },
    { index: 522, words_eng: 'for rent', translate: 'для здачі' },

    { index: 523, words_eng: 'addition', translate: 'додавання' },
    { index: 524, words_eng: 'affordable', translate: 'доступний' },
    { index: 525, words_eng: 'compare', translate: 'порівнювати' },
    { index: 526, words_eng: 'expense', translate: 'витрати' },
    { index: 527, words_eng: 'expensive', translate: 'дорогий' },
    { index: 528, words_eng: 'judge', translate: 'судити' },
    { index: 529, words_eng: 'judgement', translate: 'судження' },
    { index: 530, words_eng: 'servant', translate: 'слуга' },
    { index: 531, words_eng: 'truthful', translate: 'правдивий' },
    { index: 532, words_eng: 'truth', translate: 'правда' },
    { index: 533, words_eng: 'useful', translate: 'корисний, потрібний' },
    { index: 534, words_eng: 'useless', translate: 'непотрібний, марний' },
    { index: 535, words_eng: 'value', translate: 'цінувати' },
    { index: 536, words_eng: 'valuable', translate: 'цінний' },
  ],
  18: [
    { index: 537, words_eng: 'change', translate: 'дрібні гроші, здача' },
    { index: 538, words_eng: 'even', translate: 'навіть' },
    { index: 539, words_eng: 'find out', translate: 'визначати, дізнатись' },
    { index: 540, words_eng: 'label', translate: 'цінник' },
    { index: 541, words_eng: 'beg', translate: 'благати' },

    { index: 542, words_eng: 'artificial', translate: 'штучний' },
    { index: 543, words_eng: 'digital', translate: 'цифровий' },
    { index: 544, words_eng: 'estimate', translate: 'оцінювати' },
    { index: 545, words_eng: 'hardware', translate: 'опаратне забезпечення' },
    { index: 546, words_eng: 'involve', translate: 'залучати' },
    { index: 547, words_eng: 'lock', translate: 'брак, відсутність' },
    { index: 548, words_eng: 'operate', translate: 'працювати( щось)' },
    { index: 549, words_eng: 'sudden', translate: 'раптовий' },
    { index: 550, words_eng: 'come across', translate: 'наштовхнутись на' },
    { index: 551, words_eng: 'find out', translate: "з'ясувати" },
    { index: 552, words_eng: 'make up', translate: 'дійти до висновку' },
    { index: 553, words_eng: 'pull off', translate: 'вирвати' },
    { index: 554, words_eng: 'throw away', translate: 'викинути' },
    { index: 555, words_eng: 'at last', translate: 'нарешті' },
    { index: 556, words_eng: 'out of order', translate: 'зламаний' },
    { index: 557, words_eng: 'chemist', translate: 'хімік' },
    { index: 558, words_eng: 'chemistry', translate: 'хімія' },
    { index: 559, words_eng: 'conclude', translate: 'робити висновок' },
    { index: 560, words_eng: 'conclusion', translate: 'висновок' },
    { index: 561, words_eng: 'examine', translate: 'перевіряти' },
    { index: 562, words_eng: 'fascinate', translate: 'зачаровувати' },
    { index: 563, words_eng: 'fascination', translate: 'захоплення' },
  ],
  21: [
    { index: 564, words_eng: 'accent', translate: 'наголос' },
    { index: 565, words_eng: 'announcement', translate: 'оголошення' },
    { index: 566, words_eng: 'broadcast', translate: 'пряма трансліція' },
    { index: 567, words_eng: 'pause', translate: 'пауза' },
    { index: 568, words_eng: 'persuade', translate: 'перекнувати' },
    { index: 569, words_eng: 'signal', translate: 'сигнал' },
    { index: 570, words_eng: 'swear', translate: 'лаятись, матюкатись' },
    { index: 571, words_eng: 'whisper', translate: 'шепіт, шепотіти' },
    { index: 572, words_eng: 'come out', translate: 'зізнаватись, бути публікованим' },
    { index: 573, words_eng: 'cut off', translate: 'відʼєднаний від цивілізації' },
    { index: 574, words_eng: 'fill in', translate: 'заповнити форму' },
    { index: 575, words_eng: 'hang up', translate: 'закінчити дзвінок' },
    { index: 576, words_eng: 'receiver', translate: 'приймач, одержувач' },
    { index: 577, words_eng: 'put down', translate: 'поставити, опустити' },
    { index: 578, words_eng: 'log off', translate: 'не мати зʼєднання із інетрнетом, сайтом' },
    { index: 579, words_eng: 'log in', translate: 'мати зʼєднання із інтернетом' },
    { index: 580, words_eng: 'print out', translate: 'родрукувати' },
    { index: 581, words_eng: 'by phone', translate: 'за допомогою телефона' },
    { index: 582, words_eng: 'certain', translate: 'певний' },
    { index: 583, words_eng: 'certainly', translate: 'звичайно! звісно ж' },
    { index: 584, words_eng: 'certainty', translate: 'певність' },
    { index: 585, words_eng: 'deliver', translate: 'доставка покупок' },
    { index: 586, words_eng: 'express', translate: 'виражати' },
    { index: 587, words_eng: 'prediction', translate: 'передбачення' },
    { index: 588, words_eng: 'predict', translate: 'передбачати' },
    { index: 589, words_eng: 'secrecy', translate: 'таємниця, секретність' },
    { index: 590, words_eng: 'unpredictable', translate: 'непередбачуваний' },
    { index: 591, words_eng: 'glance at', translate: 'глянути на, зиркнути' },
    { index: 592, words_eng: 'receive sth from', translate: 'отримати щось від' },
    { index: 593, words_eng: 'reply to', translate: 'відповісти на щось' },
    { index: 594, words_eng: 'talk to sm about ', translate: 'говорити із кимось про' },
    {
      index: 595,
      words_eng: 'translate from sth into',
      translate: 'перекласти щось на якусь мову',
    },
  ],
  24: [
    { index: 596, words_eng: 'admit', translate: 'зізнаватись, визнавати провину' },
    { index: 597, words_eng: 'commit', translate: "взяти на себе зобов'язання" },
    { index: 598, words_eng: 'community', translate: 'спільнота' },
    { index: 599, words_eng: 'court', translate: 'суд' },
    { index: 600, words_eng: 'familiar', translate: 'знайомий' },
    { index: 601, words_eng: 'habit', translate: 'звичка' },
    { index: 602, words_eng: 'illegal', translate: 'нелегальний' },
    { index: 603, words_eng: 'politics', translate: 'політика' },
    { index: 604, words_eng: 'population', translate: 'населення' },
    { index: 605, words_eng: 'resident', translate: 'житель (міста, країни)' },
    { index: 606, words_eng: 'responsible', translate: 'відповідальний' },
    { index: 607, words_eng: 'schedule', translate: 'розклад' },
    { index: 608, words_eng: 'society', translate: 'суспільство' },
    { index: 609, words_eng: 'youth club', translate: 'молодіжний клуб' },
    { index: 610, words_eng: 'break into', translate: 'вламатись до' },
    { index: 611, words_eng: 'catch up', translate: 'догнати, зрівнятись із' },
    { index: 612, words_eng: 'get away with', translate: 'уникнути покарання' },
    { index: 613, words_eng: 'get up', translate: 'встати із ліжка' },
    { index: 614, words_eng: 'move in', translate: 'переїхати (в будинок)' },
    { index: 615, words_eng: 'put away', translate: 'повернути на місце де було' },
    { index: 616, words_eng: 'cutlery', translate: 'столові прибори' },
    { index: 617, words_eng: 'in response to', translate: 'у відповідь на' },
    { index: 618, words_eng: 'in touch with', translate: 'підтримуваи спілкування' },
    { index: 619, words_eng: 'belief', translate: 'переконання' },
    { index: 620, words_eng: 'courage', translate: 'мужність, відважність' },
    { index: 621, words_eng: 'courageous', translate: 'відважний, міжній' },
    { index: 622, words_eng: 'elect', translate: 'обрати, обраний' },
    { index: 623, words_eng: 'election', translate: 'вибори' },
    { index: 624, words_eng: 'nation', translate: 'нація' },
    { index: 625, words_eng: 'peaceful', translate: 'мирний' },
    { index: 626, words_eng: 'prisoner', translate: 'вʼязень' },
    { index: 627, words_eng: 'shoot', translate: 'стріляти' },
    { index: 628, words_eng: 'shot', translate: 'постріл' },
    { index: 629, words_eng: 'shooting', translate: 'розстріл, стрілянина' },
    { index: 630, words_eng: 'angry with sb about', translate: 'злий на когось за щось' },
    { index: 631, words_eng: 'guilty of', translate: 'винний за' },
    { index: 632, words_eng: 'accuse sb of', translate: 'звинувачувати когось в (офіційне)' },
    { index: 633, words_eng: 'blame sb of', translate: 'звинувачувати когось в' },
    { index: 634, words_eng: 'blame sth on', translate: 'звинувачувати щось в' },
    { index: 635, words_eng: 'criticise sb for', translate: 'критикувати за' },
    { index: 636, words_eng: 'punish sb for', translate: 'покарати когось за' },
    { index: 637, words_eng: 'share sth with', translate: 'ділити щось з' },
    { index: 638, words_eng: 'smile at', translate: 'посміхнутись комусь' },

    { index: 639, words_eng: 'obvious', translate: 'очевидне' },
    { index: 640, words_eng: 'observant', translate: 'спостережливий' },
    { index: 641, words_eng: 'handy', translate: 'зручний' },
    { index: 642, words_eng: 'suspect', translate: 'підозрюваний' },
    { index: 643, words_eng: 'head boy', translate: 'староста' },
    { index: 644, words_eng: 'bloody hell', translate: 'Черт візьми!' },
    { index: 645, words_eng: 'clue', translate: 'підказка' },
    { index: 646, words_eng: 'hint', translate: 'натяк, намьок' },
    { index: 647, words_eng: 'Nothing more or less', translate: 'не більше не меше' },
  ],
  27: [
    { index: 648, words_eng: 'ambition', translate: 'амбіція' },
    { index: 649, words_eng: 'deserve', translate: 'заслуговувати' },
    { index: 650, words_eng: 'earn', translate: 'заробляти' },
    { index: 651, words_eng: 'fame', translate: 'слава' },
    { index: 652, words_eng: 'goal', translate: 'мета' },
    { index: 653, words_eng: 'impress', translate: 'враження' },
    { index: 654, words_eng: 'income', translate: 'дохід' },
    { index: 655, words_eng: 'poverty', translate: 'бідність' },
    { index: 656, words_eng: 'pressure', translate: 'тиск' },
    { index: 657, words_eng: 'retire', translate: 'виходити на пенсію' },
    { index: 658, words_eng: 'fax', translate: 'налог, податок' },
    { index: 659, words_eng: 'wealthy', translate: 'багатий, заможній' },
    { index: 660, words_eng: 'wage', translate: 'зарплата за певний окрес' },
    { index: 661, words_eng: 'pension', translate: 'пенсія' },
    { index: 662, words_eng: 'call off', translate: 'відмінити' },
    { index: 663, words_eng: 'give back', translate: 'вернути де взяв' },
    { index: 664, words_eng: 'put off', translate: 'відкласти на пізніше' },
    { index: 665, words_eng: 'set up', translate: 'почати щось( бізнес, ..)' },
    { index: 666, words_eng: 'stay up', translate: 'піти пізніше спати' },
    { index: 667, words_eng: 'take away', translate: 'видалити' },
    { index: 668, words_eng: 'take over', translate: 'очолити( бізнес, ....)' },
    { index: 669, words_eng: 'be in charge of', translate: 'бути відповідальним' },
    { index: 670, words_eng: 'beggar', translate: 'той хто вічно просить' },
    { index: 671, words_eng: 'occupation', translate: 'професія' },
    { index: 672, words_eng: 'fed up with', translate: 'набридно щось' },
    { index: 673, words_eng: 'be about to', translate: 'збирається, ось-ось' },
    { index: 674, words_eng: 'cell', translate: 'камера, комірка' },
    { index: 675, words_eng: 'wrist', translate: 'запʼястя' },
    { index: 676, words_eng: 'puff', translate: 'затяжка' },
    { index: 677, words_eng: 'take a puff', translate: 'робити затяжку' },
    { index: 678, words_eng: 'thumb', translate: 'великий палець' },
    { index: 679, words_eng: 'tip', translate: 'кінець чогось( пальця)' },
    { index: 680, words_eng: 'index finder', translate: 'вказівний палець' },
    { index: 681, words_eng: 'statement', translate: 'заява, звіт' },
    { index: 682, words_eng: 'earn', translate: 'заробляти' },
    { index: 683, words_eng: 'gross', translate: 'мерзість, гидота' },
    { index: 684, words_eng: 'put out', translate: 'гасити' },
  ],
  30: [
    { index: 724, words_eng: 'affect', translate: 'мати ефект, впливати' },
    { index: 725, words_eng: 'breathe', translate: 'дихати' },
    { index: 726, words_eng: 'chew', translate: 'жувати' },
    { index: 727, words_eng: 'chop', translate: 'різати на кубіки' },
    { index: 728, words_eng: 'cough', translate: 'кашляти, кашель' },
    { index: 729, words_eng: 'cure for', translate: 'лікувати, ліки' },
    { index: 730, words_eng: 'flu', translate: 'грип' },
    { index: 731, words_eng: 'injury', translate: 'травма' },
    { index: 732, words_eng: 'pill', translate: 'таблетки' },
    { index: 733, words_eng: 'recover from', translate: 'одужувати' },
    { index: 734, words_eng: 'salty', translate: 'солений' },
    { index: 735, words_eng: 'slice', translate: 'шматочок (тонко нарізаний, слайс)' },
    { index: 736, words_eng: 'spicy', translate: 'гострий' },
    { index: 737, words_eng: 'stir', translate: 'перемішувати' },
    { index: 738, words_eng: 'suffer', translate: 'страждати' },
    { index: 739, words_eng: 'treatment', translate: 'лікування' },
    { index: 740, words_eng: 'cut down', translate: 'скоротити робити щось' },
    { index: 741, words_eng: 'fall down', translate: 'провалитись' },
    { index: 742, words_eng: 'get over', translate: 'видужати від' },
    { index: 743, words_eng: 'go off', translate: 'не бути свіжим' },
    { index: 744, words_eng: 'lie down', translate: 'лягти на ліжко' },
    { index: 745, words_eng: 'put on', translate: 'набрати вагу' },
    { index: 746, words_eng: 'in comparison to', translate: 'у порівнянні з' },
    { index: 747, words_eng: 'in shape', translate: 'в гарній формі' },
    { index: 748, words_eng: 'on a diet', translate: 'на дієті' },
    { index: 749, words_eng: 'bakery', translate: 'пекарня' },
    { index: 750, words_eng: 'bend', translate: 'гнути' },
    { index: 751, words_eng: 'cooker', translate: 'плита' },
    { index: 752, words_eng: 'cookery', translate: 'кулінарія' },
    { index: 753, words_eng: 'intend', translate: 'мати намір' },
    { index: 754, words_eng: 'intention', translate: 'намірення' },
    { index: 755, words_eng: 'intentional', translate: 'навмисний' },
    { index: 756, words_eng: 'jog', translate: 'біг( пробіжна)' },
    { index: 757, words_eng: 'jogging', translate: 'бігти' },
    { index: 758, words_eng: 'jogger', translate: 'бігун' },
    { index: 759, words_eng: 'medicine', translate: 'ліки' },
    { index: 760, words_eng: 'reduce', translate: 'зменшити' },
    { index: 761, words_eng: 'reduction', translate: 'зменшення' },
    { index: 762, words_eng: 'sensible', translate: 'розумний' },
    { index: 763, words_eng: 'sensitive', translate: 'чутливий' },
    { index: 764, words_eng: 'weigh', translate: 'важити' },
    { index: 765, words_eng: 'weight', translate: 'вага' },
    { index: 766, words_eng: 'addicted to', translate: 'залежний від (наркотики, алкогось)' },
    { index: 767, words_eng: 'pleased with', translate: 'задоволений від' },
    { index: 768, words_eng: 'complain about', translate: 'скаржитись на' },
    { index: 769, words_eng: 'die from', translate: 'померти від' },
    { index: 770, words_eng: 'smell of', translate: 'запах від' },
    { index: 771, words_eng: 'roast', translate: 'запікати в духовці або на вогні' },
  ],
  '33 1': [
    { index: 772, words_eng: 'sour', translate: 'кислий' },
    { index: 773, words_eng: 'ancient', translate: 'давній' },
    { index: 774, words_eng: 'cotton', translate: 'бавовна' },
    { index: 775, words_eng: 'fold', translate: 'складати, згортати' },
    { index: 776, words_eng: 'improvement', translate: 'покращення' },
    { index: 777, words_eng: 'loose', translate: 'широкий, вільний, не точний' },
    { index: 778, words_eng: 'maintain', translate: 'підтримувати, керувати' },
    { index: 779, words_eng: 'match', translate: 'поєднювати' },
    { index: 780, words_eng: 'pile', translate: 'купа (чогось)' },
    { index: 781, words_eng: 'rough', translate: 'грибий (щось), неточний' },
    { index: 782, words_eng: 'shape', translate: 'форма' },
    { index: 783, words_eng: 'silk', translate: 'шофк' },
    { index: 784, words_eng: 'sleeve', translate: 'рукав' },
    { index: 785, words_eng: 'smooth', translate: 'гладкий' },
    { index: 786, words_eng: 'stretch', translate: 'розтягувати' },
    { index: 787, words_eng: 'striped', translate: 'волосатий' },
    { index: 788, words_eng: 'suit', translate: 'костюм' },
    { index: 789, words_eng: 'tear', translate: 'сльоза, рвати(на куски)' },
    { index: 790, words_eng: 'tight', translate: 'тісний' },
    { index: 791, words_eng: 'tool', translate: 'інтструмент' },
  ],
  '33 2': [
    { index: 792, words_eng: 'cut off', translate: 'відрізати' },
    { index: 793, words_eng: 'do up', translate: 'підняти замок (на кофті)' },
    { index: 794, words_eng: 'fill up', translate: 'заповнити' },
    { index: 795, words_eng: 'have on', translate: 'одягнути' },
    { index: 796, words_eng: 'leave out', translate: 'не включати ( поза комплтом)' },
    { index: 797, words_eng: 'put on', translate: 'почати носити' },
    { index: 798, words_eng: 'take off', translate: 'зняти одяг' },
    { index: 799, words_eng: 'try on', translate: 'приміряти' },
    { index: 800, words_eng: 'artist', translate: 'художник' },
    { index: 801, words_eng: 'unbreakable', translate: 'незламний (щось)' },
    { index: 802, words_eng: 'compose', translate: 'складати' },
    { index: 803, words_eng: 'composer', translate: 'композитор' },
    { index: 804, words_eng: 'exhibit', translate: 'виставляти' },
    { index: 805, words_eng: 'exhibition', translate: 'виставка' },
    { index: 806, words_eng: 'freedom', translate: 'свобода' },
    { index: 807, words_eng: 'handful', translate: 'жменя, той хто пригощає' },
    { index: 808, words_eng: 'handle', translate: 'рукоятка, справлятись' },
    { index: 809, words_eng: 'imaginative', translate: 'уявний' },
    { index: 810, words_eng: 'intelligent', translate: 'розумний' },
    { index: 811, words_eng: 'intelligence', translate: 'інтелект' },
    { index: 812, words_eng: 'imperfect', translate: 'неідеальний' },
    { index: 813, words_eng: 'amazed by', translate: 'вражений чимось' },
    { index: 814, words_eng: 'familiar with', translate: 'знайомий з' },
    { index: 815, words_eng: 'explain sth to', translate: 'пояснити щось комусь' },
    { index: 816, words_eng: 'remind sb of', translate: 'нагадати комусь про' },
  ],
};
